# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'AnlikKadin_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AnlikKadn_window(object):
    def setupUi(self, AnlikKadn_window):
        AnlikKadn_window.setObjectName("AnlikKadn_window")
        AnlikKadn_window.resize(314, 73)
        AnlikKadn_window.setMinimumSize(QtCore.QSize(314, 73))
        AnlikKadn_window.setMouseTracking(False)
        self.pushButton_BaslatK = QtWidgets.QPushButton(AnlikKadn_window)
        self.pushButton_BaslatK.setGeometry(QtCore.QRect(30, 20, 93, 28))
        self.pushButton_BaslatK.setObjectName("pushButton_BaslatK")
        self.pushButton_DurdurK = QtWidgets.QPushButton(AnlikKadn_window)
        self.pushButton_DurdurK.setGeometry(QtCore.QRect(160, 20, 93, 28))
        self.pushButton_DurdurK.setObjectName("pushButton_DurdurK")

        self.retranslateUi(AnlikKadn_window)
        QtCore.QMetaObject.connectSlotsByName(AnlikKadn_window)

    def retranslateUi(self, AnlikKadn_window):
        _translate = QtCore.QCoreApplication.translate
        AnlikKadn_window.setWindowTitle(_translate("AnlikKadn_window", "Form"))
        self.pushButton_BaslatK.setText(_translate("AnlikKadn_window", "Baslat"))
        self.pushButton_DurdurK.setText(_translate("AnlikKadn_window", "Durdur"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    AnlikKadn_window = QtWidgets.QWidget()
    ui = Ui_AnlikKadn_window()
    ui.setupUi(AnlikKadn_window)
    AnlikKadn_window.show()
    sys.exit(app.exec_())
