# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'AnlikErkek_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Anlik_Erkek_Window(object):
    def setupUi(self, Anlik_Erkek_Window):
        Anlik_Erkek_Window.setObjectName("Anlik_Erkek_Window")
        Anlik_Erkek_Window.resize(295, 107)
        Anlik_Erkek_Window.setMinimumSize(QtCore.QSize(295, 107))
        Anlik_Erkek_Window.setMouseTracking(False)
        Anlik_Erkek_Window.setTabletTracking(False)
        self.pushButton_BaslatE = QtWidgets.QPushButton(Anlik_Erkek_Window)
        self.pushButton_BaslatE.setGeometry(QtCore.QRect(40, 30, 93, 28))
        self.pushButton_BaslatE.setObjectName("pushButton_BaslatE")
        self.pushButton_DurdurK = QtWidgets.QPushButton(Anlik_Erkek_Window)
        self.pushButton_DurdurK.setGeometry(QtCore.QRect(160, 30, 93, 28))
        self.pushButton_DurdurK.setObjectName("pushButton_DurdurK")

        self.retranslateUi(Anlik_Erkek_Window)
        QtCore.QMetaObject.connectSlotsByName(Anlik_Erkek_Window)

    def retranslateUi(self, Anlik_Erkek_Window):
        _translate = QtCore.QCoreApplication.translate
        Anlik_Erkek_Window.setWindowTitle(_translate("Anlik_Erkek_Window", "Form"))
        self.pushButton_BaslatE.setText(_translate("Anlik_Erkek_Window", "Başlat"))
        self.pushButton_DurdurK.setText(_translate("Anlik_Erkek_Window", "Durdur"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Anlik_Erkek_Window = QtWidgets.QWidget()
    ui = Ui_Anlik_Erkek_Window()
    ui.setupUi(Anlik_Erkek_Window)
    Anlik_Erkek_Window.show()
    sys.exit(app.exec_())
