# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'istemci.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(753, 670)
        Dialog.setMinimumSize(QtCore.QSize(753, 670))
        self.ip_grup_box = QtWidgets.QGroupBox(Dialog)
        self.ip_grup_box.setGeometry(QtCore.QRect(20, 20, 351, 371))
        self.ip_grup_box.setObjectName("ip_grup_box")
        self.ip_combobox = QtWidgets.QComboBox(self.ip_grup_box)
        self.ip_combobox.setGeometry(QtCore.QRect(30, 30, 111, 22))
        self.ip_combobox.setObjectName("ip_combobox")
        self.ip_tara_buton = QtWidgets.QPushButton(self.ip_grup_box)
        self.ip_tara_buton.setGeometry(QtCore.QRect(160, 30, 81, 28))
        self.ip_tara_buton.setObjectName("ip_tara_buton")
        self.ip_listesi = QtWidgets.QListWidget(self.ip_grup_box)
        self.ip_listesi.setGeometry(QtCore.QRect(30, 80, 271, 191))
        self.ip_listesi.setObjectName("ip_listesi")
        self.otomatik_baglan_buton = QtWidgets.QPushButton(self.ip_grup_box)
        self.otomatik_baglan_buton.setGeometry(QtCore.QRect(120, 290, 93, 28))
        self.otomatik_baglan_buton.setObjectName("otomatik_baglan_buton")
        self.manuel_baglan = QtWidgets.QPushButton(self.ip_grup_box)
        self.manuel_baglan.setGeometry(QtCore.QRect(250, 30, 71, 28))
        self.manuel_baglan.setObjectName("manuel_baglan")
        self.ses_islem_grunBox = QtWidgets.QGroupBox(Dialog)
        self.ses_islem_grunBox.setGeometry(QtCore.QRect(410, 20, 281, 371))
        self.ses_islem_grunBox.setObjectName("ses_islem_grunBox")
        self.ses_gonder_buton = QtWidgets.QPushButton(self.ses_islem_grunBox)
        self.ses_gonder_buton.setGeometry(QtCore.QRect(12, 50, 101, 28))
        self.ses_gonder_buton.setObjectName("ses_gonder_buton")
        self.Ses_gonder_dur = QtWidgets.QPushButton(self.ses_islem_grunBox)
        self.Ses_gonder_dur.setGeometry(QtCore.QRect(120, 50, 151, 28))
        self.Ses_gonder_dur.setObjectName("Ses_gonder_dur")
        self.ses_al_devam = QtWidgets.QPushButton(self.ses_islem_grunBox)
        self.ses_al_devam.setGeometry(QtCore.QRect(20, 140, 101, 28))
        self.ses_al_devam.setObjectName("ses_al_devam")
        self.ses_al_duraklat = QtWidgets.QPushButton(self.ses_islem_grunBox)
        self.ses_al_duraklat.setGeometry(QtCore.QRect(150, 140, 111, 28))
        self.ses_al_duraklat.setObjectName("ses_al_duraklat")
        self.baglantiyi_kes_buton = QtWidgets.QPushButton(self.ses_islem_grunBox)
        self.baglantiyi_kes_buton.setGeometry(QtCore.QRect(90, 240, 101, 28))
        self.baglantiyi_kes_buton.setObjectName("baglantiyi_kes_buton")
        self.metin_grupBox = QtWidgets.QGroupBox(Dialog)
        self.metin_grupBox.setGeometry(QtCore.QRect(170, 420, 441, 201))
        self.metin_grupBox.setObjectName("metin_grupBox")
        self.metin_yeri = QtWidgets.QTextEdit(self.metin_grupBox)
        self.metin_yeri.setGeometry(QtCore.QRect(60, 20, 331, 111))
        self.metin_yeri.setObjectName("metin_yeri")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.ip_grup_box.setTitle(_translate("Dialog", "ip tarama"))
        self.ip_tara_buton.setText(_translate("Dialog", "IP tara"))
        self.otomatik_baglan_buton.setText(_translate("Dialog", "Otomatik Bağlan"))
        self.manuel_baglan.setText(_translate("Dialog", "Manuel Bağlan"))
        self.ses_islem_grunBox.setTitle(_translate("Dialog", "ses işlemleri"))
        self.ses_gonder_buton.setText(_translate("Dialog", "Ses Gönder"))
        self.Ses_gonder_dur.setText(_translate("Dialog", "Ses gönermeyi durdur"))
        self.ses_al_devam.setText(_translate("Dialog", "Ses al-devam"))
        self.ses_al_duraklat.setText(_translate("Dialog", "Ses al-duraklat"))
        self.baglantiyi_kes_buton.setText(_translate("Dialog", "Bağlantıyı kes"))
        self.metin_grupBox.setTitle(_translate("Dialog", "Metin işlemleri"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
