# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'kayit_yeri.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_girisyeri(object):
    def setupUi(self, girisyeri):
        girisyeri.setObjectName("girisyeri")
        girisyeri.resize(596, 344)
        girisyeri.setMinimumSize(QtCore.QSize(596, 344))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        girisyeri.setFont(font)
        self.centralwidget = QtWidgets.QWidget(girisyeri)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(220, 10, 141, 31))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(10, 60, 291, 201))
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.pushButton = QtWidgets.QPushButton(self.groupBox)
        self.pushButton.setGeometry(QtCore.QRect(110, 160, 93, 28))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(20, 20, 121, 16))
        self.label_2.setObjectName("label_2")
        self.kullanici_ad_yeri = QtWidgets.QLineEdit(self.groupBox)
        self.kullanici_ad_yeri.setGeometry(QtCore.QRect(110, 60, 113, 22))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.kullanici_ad_yeri.setFont(font)
        self.kullanici_ad_yeri.setObjectName("kullanici_ad_yeri")
        self.kullanici_ad_qlabel = QtWidgets.QLabel(self.groupBox)
        self.kullanici_ad_qlabel.setGeometry(QtCore.QRect(10, 60, 101, 21))
        self.kullanici_ad_qlabel.setObjectName("kullanici_ad_qlabel")
        self.sifre_yeri = QtWidgets.QLineEdit(self.groupBox)
        self.sifre_yeri.setGeometry(QtCore.QRect(110, 100, 113, 22))
        self.sifre_yeri.setObjectName("sifre_yeri")
        self.sifre_qlabel = QtWidgets.QLabel(self.groupBox)
        self.sifre_qlabel.setGeometry(QtCore.QRect(10, 100, 71, 21))
        self.sifre_qlabel.setObjectName("sifre_qlabel")
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(320, 70, 261, 111))
        self.groupBox_2.setObjectName("groupBox_2")
        self.kayit_buton = QtWidgets.QPushButton(self.groupBox_2)
        self.kayit_buton.setGeometry(QtCore.QRect(60, 50, 141, 28))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.kayit_buton.setFont(font)
        self.kayit_buton.setObjectName("kayit_buton")
        girisyeri.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(girisyeri)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 596, 26))
        self.menubar.setObjectName("menubar")
        girisyeri.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(girisyeri)
        self.statusbar.setObjectName("statusbar")
        girisyeri.setStatusBar(self.statusbar)

        self.retranslateUi(girisyeri)
        QtCore.QMetaObject.connectSlotsByName(girisyeri)

    def retranslateUi(self, girisyeri):
        _translate = QtCore.QCoreApplication.translate
        girisyeri.setWindowTitle(_translate("girisyeri", "MainWindow"))
        self.label.setText(_translate("girisyeri", "<html><head/><body><p align=\"center\"><span style=\" font-size:11pt; font-style:italic; color:#ff0c40;\">Üye Girişi</span></p></body></html>"))
        self.pushButton.setText(_translate("girisyeri", "Giriş yap"))
        self.label_2.setText(_translate("girisyeri", "Zaten Üye misiniz"))
        self.kullanici_ad_qlabel.setText(_translate("girisyeri", "<html><head/><body><p><span style=\" font-weight:400;\">Kullanıcı adı :</span></p></body></html>"))
        self.sifre_qlabel.setText(_translate("girisyeri", "<html><head/><body><p><span style=\" font-weight:400;\">Şifre :</span></p></body></html>"))
        self.groupBox_2.setTitle(_translate("girisyeri", "Üye değilseniz kaydolmak için tıklayın"))
        self.kayit_buton.setText(_translate("girisyeri", "kayıt İçin tıkla"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    girisyeri = QtWidgets.QMainWindow()
    ui = Ui_girisyeri()
    ui.setupUi(girisyeri)
    girisyeri.show()
    sys.exit(app.exec_())
