# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Ses_Kaydi.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Ses_kaydi_window(object):
    def setupUi(self, Ses_kaydi_window):
        Ses_kaydi_window.setObjectName("Ses_kaydi_window")
        Ses_kaydi_window.resize(514, 59)
        self.pushButton_SesKayd_baslat = QtWidgets.QPushButton(Ses_kaydi_window)
        self.pushButton_SesKayd_baslat.setGeometry(QtCore.QRect(10, 10, 93, 28))
        self.pushButton_SesKayd_baslat.setObjectName("pushButton_SesKayd_baslat")
        self.pushButton_SesK_Durdur = QtWidgets.QPushButton(Ses_kaydi_window)
        self.pushButton_SesK_Durdur.setGeometry(QtCore.QRect(130, 10, 93, 28))
        self.pushButton_SesK_Durdur.setObjectName("pushButton_SesK_Durdur")
        self.lineEdit_Cinsiyet_text = QtWidgets.QLineEdit(Ses_kaydi_window)
        self.lineEdit_Cinsiyet_text.setGeometry(QtCore.QRect(280, 10, 201, 31))
        self.lineEdit_Cinsiyet_text.setObjectName("lineEdit_Cinsiyet_text")

        self.retranslateUi(Ses_kaydi_window)
        QtCore.QMetaObject.connectSlotsByName(Ses_kaydi_window)

    def retranslateUi(self, Ses_kaydi_window):
        _translate = QtCore.QCoreApplication.translate
        Ses_kaydi_window.setWindowTitle(_translate("Ses_kaydi_window", "Form"))
        self.pushButton_SesKayd_baslat.setText(_translate("Ses_kaydi_window", "Baslat"))
        self.pushButton_SesK_Durdur.setText(_translate("Ses_kaydi_window", "Durdur"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Ses_kaydi_window = QtWidgets.QWidget()
    ui = Ui_Ses_kaydi_window()
    ui.setupUi(Ses_kaydi_window)
    Ses_kaydi_window.show()
    sys.exit(app.exec_())
